version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/site:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL
    ports:
      - "8000:8000"
